# Generated by Django 4.2.7 on 2023-11-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="city",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
